-- MySQL Script generated by MySQL Workbench
-- Sun Jun 24 18:05:14 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Locadora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Locadora` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Locadora` (
  `CNPJ` VARCHAR(20) NOT NULL,
  `Cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`CNPJ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Filme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Filme` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Filme` (
  `ID` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Preço` FLOAT NULL,
  `Categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `Sigla` VARCHAR(5) NOT NULL,
  `Categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`Sigla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionário`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Funcionário` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Funcionário` (
  `CPF` VARCHAR(20) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Data_Contratação` VARCHAR(12) NULL,
  `Locadora_CNPJ` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`CPF`),
  INDEX `fk_Funcionário_Locadora1_idx` (`Locadora_CNPJ` ASC),
  CONSTRAINT `fk_Funcionário_Locadora1`
    FOREIGN KEY (`Locadora_CNPJ`)
    REFERENCES `mydb`.`Locadora` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Locadora_has_Filme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Locadora_has_Filme` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Locadora_has_Filme` (
  `Locadora_CNPJ` VARCHAR(20) NOT NULL,
  `Filme_ID` INT NOT NULL,
  PRIMARY KEY (`Locadora_CNPJ`, `Filme_ID`),
  INDEX `fk_Locadora_has_Filme_Filme1_idx` (`Filme_ID` ASC),
  INDEX `fk_Locadora_has_Filme_Locadora1_idx` (`Locadora_CNPJ` ASC),
  CONSTRAINT `fk_Locadora_has_Filme_Locadora1`
    FOREIGN KEY (`Locadora_CNPJ`)
    REFERENCES `mydb`.`Locadora` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locadora_has_Filme_Filme1`
    FOREIGN KEY (`Filme_ID`)
    REFERENCES `mydb`.`Filme` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Filme_has_Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Filme_has_Categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Filme_has_Categoria` (
  `Filme_ID` INT NOT NULL,
  `Categoria_Sigla` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`Filme_ID`, `Categoria_Sigla`),
  INDEX `fk_Filme_has_Categoria_Categoria1_idx` (`Categoria_Sigla` ASC),
  INDEX `fk_Filme_has_Categoria_Filme1_idx` (`Filme_ID` ASC),
  CONSTRAINT `fk_Filme_has_Categoria_Filme1`
    FOREIGN KEY (`Filme_ID`)
    REFERENCES `mydb`.`Filme` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Filme_has_Categoria_Categoria1`
    FOREIGN KEY (`Categoria_Sigla`)
    REFERENCES `mydb`.`Categoria` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
