-- MySQL Script generated by MySQL Workbench
-- Wed Jun 20 18:24:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Locadora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Locadora` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Locadora` (
  `CNPJ` VARCHAR(20) NOT NULL,
  `cidade` VARCHAR(100) NULL,
  PRIMARY KEY (`CNPJ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `preco` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `nomeCategoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionário`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Funcionário` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Funcionário` (
  `idFuncionario` INT NOT NULL,
  `nomeFuncionario` VARCHAR(45) NULL,
  `dataContratacao` DATE NULL,
  `Locadora_CNPJ` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`idFuncionario`, `Locadora_CNPJ`),
  INDEX `fk_Funcionário_Locadora1_idx` (`Locadora_CNPJ` ASC),
  CONSTRAINT `fk_Funcionário_Locadora1`
    FOREIGN KEY (`Locadora_CNPJ`)
    REFERENCES `mydb`.`Locadora` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `CPF` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `telefone` INT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionário_has_Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Funcionário_has_Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Funcionário_has_Cliente` (
  `Funcionário_idFuncionario` INT NOT NULL,
  `Cliente_CPF` INT NOT NULL,
  `dataContratacao` DATETIME NULL,
  PRIMARY KEY (`Funcionário_idFuncionario`, `Cliente_CPF`),
  INDEX `fk_Funcionário_has_Cliente_Cliente1_idx` (`Cliente_CPF` ASC),
  INDEX `fk_Funcionário_has_Cliente_Funcionário1_idx` (`Funcionário_idFuncionario` ASC),
  CONSTRAINT `fk_Funcionário_has_Cliente_Funcionário1`
    FOREIGN KEY (`Funcionário_idFuncionario`)
    REFERENCES `mydb`.`Funcionário` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionário_has_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_CPF`)
    REFERENCES `mydb`.`Cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `dataPedido` DATETIME NULL,
  `Funcionário_has_Cliente_Funcionário_idFuncionario` INT NOT NULL,
  `Funcionário_has_Cliente_Cliente_CPF` INT NOT NULL,
  `preco` FLOAT NULL,
  PRIMARY KEY (`idPedido`, `Funcionário_has_Cliente_Funcionário_idFuncionario`, `Funcionário_has_Cliente_Cliente_CPF`),
  INDEX `fk_Pedido_Funcionário_has_Cliente1_idx` (`Funcionário_has_Cliente_Funcionário_idFuncionario` ASC, `Funcionário_has_Cliente_Cliente_CPF` ASC),
  CONSTRAINT `fk_Pedido_Funcionário_has_Cliente1`
    FOREIGN KEY (`Funcionário_has_Cliente_Funcionário_idFuncionario` , `Funcionário_has_Cliente_Cliente_CPF`)
    REFERENCES `mydb`.`Funcionário_has_Cliente` (`Funcionário_idFuncionario` , `Cliente_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Locadora_has_Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Locadora_has_Produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Locadora_has_Produto` (
  `Locadora_CNPJ` VARCHAR(7) NOT NULL,
  `Produto_id` INT NOT NULL,
  PRIMARY KEY (`Locadora_CNPJ`, `Produto_id`),
  INDEX `fk_Locadora_has_Produto_Produto1_idx` (`Produto_id` ASC),
  INDEX `fk_Locadora_has_Produto_Locadora1_idx` (`Locadora_CNPJ` ASC),
  CONSTRAINT `fk_Locadora_has_Produto_Locadora1`
    FOREIGN KEY (`Locadora_CNPJ`)
    REFERENCES `mydb`.`Locadora` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locadora_has_Produto_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `mydb`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto_has_Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto_has_Pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produto_has_Pedido` (
  `Produto_id` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Funcionário_has_Cliente_Funcionário_idFuncionario` INT NOT NULL,
  `Pedido_Funcionário_has_Cliente_Cliente_CPF` INT NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`Produto_id`, `Pedido_idPedido`, `Pedido_Funcionário_has_Cliente_Funcionário_idFuncionario`, `Pedido_Funcionário_has_Cliente_Cliente_CPF`),
  INDEX `fk_Produto_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Funcionário_has_Cliente_Funcionário_idFuncionario` ASC, `Pedido_Funcionário_has_Cliente_Cliente_CPF` ASC),
  INDEX `fk_Produto_has_Pedido_Produto1_idx` (`Produto_id` ASC),
  CONSTRAINT `fk_Produto_has_Pedido_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `mydb`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Funcionário_has_Cliente_Funcionário_idFuncionario` , `Pedido_Funcionário_has_Cliente_Cliente_CPF`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Funcionário_has_Cliente_Funcionário_idFuncionario` , `Funcionário_has_Cliente_Cliente_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto_has_Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto_has_Categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produto_has_Categoria` (
  `Produto_id` INT NOT NULL,
  `Filmes_categoria` INT NOT NULL,
  PRIMARY KEY (`Produto_id`, `Filmes_categoria`),
  INDEX `fk_Produto_has_Filmes_Filmes1_idx` (`Filmes_categoria` ASC),
  INDEX `fk_Produto_has_Filmes_Produto1_idx` (`Produto_id` ASC),
  CONSTRAINT `fk_Produto_has_Filmes_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `mydb`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Filmes_Filmes1`
    FOREIGN KEY (`Filmes_categoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
